languageCode = "en"
languageName = "English"
weight = 1
title = "Intelligence Hub"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "From Exploration to Enlightenment"

[params.author]
  name = "Intelligence Hub"
  email = ""
  image = "img/blowfish_logo.png"
  headline = "From Exploration to Enlightenment."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { instagram = "https://instagram.com/intelligencevenue" },
    { github = "https://github.com/leadst0rm" },
  ]